//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbiloRentals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allocation
    {
        public int AllocationID { get; set; }
        public int UserID { get; set; }
        public int RoomID { get; set; }
        public Nullable<System.DateTime> AllocationDate { get; set; }
        public Nullable<System.DateTime> MoveOutDate { get; set; }
        public string Status { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
    }
}
