//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbiloRentals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LostFoundItem
    {
        public int ItemID { get; set; }
        public int ReportedBy { get; set; }
        public string Type { get; set; }
        public string ItemDescription { get; set; }
        public string Location { get; set; }
        public System.DateTime DateReported { get; set; }
        public string Status { get; set; }
    
        public virtual User User { get; set; }
    }
}
