//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbiloRentals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceAssignment
    {
        public int AssignmentID { get; set; }
        public int RequestID { get; set; }
        public int StaffID { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public string JobStatus { get; set; }
    
        public virtual MaintenanceRequest MaintenanceRequest { get; set; }
        public virtual User User { get; set; }
    }
}
