

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UmbiloRentals.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class BuildingManagementDBEntities : DbContext
{
    public BuildingManagementDBEntities()
        : base("name=BuildingManagementDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Allocation> Allocations { get; set; }

    public virtual DbSet<Announcement> Announcements { get; set; }

    public virtual DbSet<Application> Applications { get; set; }

    public virtual DbSet<Complaint> Complaints { get; set; }

    public virtual DbSet<LostFound> LostFounds { get; set; }

    public virtual DbSet<MaintenanceAssignment> MaintenanceAssignments { get; set; }

    public virtual DbSet<MaintenanceRequest> MaintenanceRequests { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Room> Rooms { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<VisitorRequest> VisitorRequests { get; set; }

}

}

