
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UmbiloRentals.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Payment
{

    public int PaymentID { get; set; }

    public int UserID { get; set; }

    public Nullable<decimal> Amount { get; set; }

    public string ProofOfPayment { get; set; }

    public string PaymentMonth { get; set; }

    public Nullable<System.DateTime> PaymentDate { get; set; }

    public string Status { get; set; }

    public Nullable<int> VerifiedBy { get; set; }

    public Nullable<int> RoomID { get; set; }



    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

    public virtual Room Room { get; set; }

}

}
