
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UmbiloRentals.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Room
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Room()
    {

        this.Allocations = new HashSet<Allocation>();

        this.MaintenanceRequests = new HashSet<MaintenanceRequest>();

        this.Payments = new HashSet<Payment>();

    }


    public int RoomID { get; set; }

    public string RoomNumber { get; set; }

    public Nullable<decimal> MonthlyRent { get; set; }

    public string Description { get; set; }

    public string Photo { get; set; }

    public string Status { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Allocation> Allocations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MaintenanceRequest> MaintenanceRequests { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Payment> Payments { get; set; }

}

}
