//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbiloRentals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public int VisitorID { get; set; }
        public int TenantID { get; set; }
        public string VisitorName { get; set; }
        public System.DateTime ScheduledDate { get; set; }
        public string Purpose { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CheckedInTime { get; set; }
        public Nullable<int> CheckedInBy { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
